gapic_generator_version: 2.41.0
googleapis_commitish: 6f289d775912966eb0cf04bda91e5e355c998d30
libraries_bom_version: 26.38.0
libraries:
  - api_shortname: bigquery
    name_pretty: Cloud BigQuery
    product_documentation: https://cloud.google.com/bigquery
    client_documentation: https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/history
    api_description: is a fully managed, NoOps, low cost data analytics service.\nData can be streamed into BigQuery at millions of rows per second to enable real-time analysis.\nWith BigQuery you can easily deploy Petabyte-scale Databases.
    issue_tracker: https://issuetracker.google.com/savedsearches/559654
    release_level: stable
    language: java
    repo: googleapis/java-bigquery
    repo_short: java-bigquery
    distribution_name: com.google.cloud:google-cloud-bigquery
    codeowner_team: '@googleapis/api-bigquery'
    api_id: bigquery.googleapis.com
    library_type: GAPIC_MANUAL
    requires_billing: true
    recommended_package: com.google.cloud.bigquery
    GAPICs:
      - proto_path: google/api #we use a dummy path to produce a no-op
