steps:
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: ls
  args: [
    '-alt',
  ]
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: curl
  args: [
    '--header',
    'Metadata-Flavor: Google',
    'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email'
  ]
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: pwd
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: printenv
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: printenv
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [
    'config',
    'list'
  ]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [
    'config',
    'set',
    'account',
    'build-runner@cloud-java-ci-sample.iam.gserviceaccount.com'
  ]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [
    'config',
    'list',
  ]
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: bash
  args: [
    '.kokoro/populate-secrets.sh'
  ]
  env:
  - 'JOB_TYPE=samples'
  - 'GOOGLE_CLOUD_PROJECT=cloud-java-ci-sample'
  - 'SECRET_MANAGER_KEYS=java-docs-samples-service-account, java-bigquery-samples-secrets'
  - 'KOKORO_GFILE_DIR=/workspace'
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: bash
  args: [
    '.kokoro/build.sh'
  ]
  env:
  - 'JOB_TYPE=samples'
  - 'GOOGLE_CLOUD_PROJECT=cloud-java-ci-sample'
  - 'KOKORO_GFILE_DIR=/workspace'
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: echo
  args: [
    'Sample job succeeded',
  ]
timeout: 3600s
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
